version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/eksperiment
    depends_on:
      - mongo
    command: python3 manage.py runserver 0.0.0.0:8000

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - django